server:
    port: 9090

eureka:
    instance:
        hostname: eureka-server
        appname: AP注册中心
    client:
        register-with-eureka: false # 单点的时候设置为 false 禁止注册自身
        fetch-registry: false
        serviceUrl:
            defaultZone: http://admin:123456@localhost:9090/eureka
    server:
      enable-self-preservation: false
      eviction-interval-timer-in-ms: 600000

ribbon:
    eureka:
        enabled: true

spring:
    main:
        allow-bean-definition-overriding: true
    security:
      user:
        name: admin
        password: 123456